//
//  spNotificationCenterIDs.h
//  Sportplus
//
//  Created by 虎猫儿 on 15/3/12.
//  Copyright (c) 2015年 JiaZai. All rights reserved.
//

#ifndef Sportplus_spNotificationCenterIDs_h
#define Sportplus_spNotificationCenterIDs_h

#define SP_FRIEND_UPDATE @"FriendsManagementViewController"

#define SP_INVITE_UPDATE @"NOTIFICATION_SPORTS_CHOOSED"

#define NOTIFICATION_MESSAGE_UPDATED @"NOTIFICATION_MESSAGE_UPDATED"
#define NOTIFICATION_SESSION_UPDATED @"NOTIFICATION_SESSION_UPDATED"
#define NOTIFICATION_GROUP_UPDATED @"NOTIFICATION_GROUP_UPDATED"

//好友约伴
#define NOTIFICATION_SPORTS_CHOOSED @"NOTIFICATION_SPORTS_CHOOSED"
#define NOTIFICATION_STADIUM_CHOOSED @"NOTIFICATION_STADIUM_CHOOSED"
#define NOTIFICATION_TIME_CHOOSED @"NOTIFICATION_TIME_CHOOSED"
#define NOTIFICATION_FRIENDS_CHOOSED @"NOTIFICATION_FRIENDS_CHOOSED"

#endif
